-- DEFApp - Base de datos completa para Supabase
-- Ejecutar en Supabase > SQL Editor

create table if not exists clientes (
  id bigint generated by default as identity primary key,
  nro_cliente bigint generated by default as identity unique,
  razon_social text not null,
  direccion text not null,
  localidad text not null,
  telefono text not null,
  cuit_cuil text,
  created_at timestamptz default now()
);

create table if not exists stock_aberturas (
  id bigint generated by default as identity primary key,
  nro_abertura bigint generated by default as identity unique,
  modelo text not null,
  medida text not null,
  madera text not null,
  mano text not null,
  created_at timestamptz default now()
);

create table if not exists pedidos (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references clientes(id) on delete restrict,
  fecha date not null,
  total numeric(14,2) not null default 0,
  archivo_url text,
  archivo_nombre text,
  nota text,
  created_at timestamptz default now()
);

alter table pedidos add column if not exists archivo_url text;
alter table pedidos add column if not exists archivo_nombre text;
alter table pedidos add column if not exists nota text;

create table if not exists pedido_items (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references pedidos(id) on delete cascade,
  abertura_id bigint not null references stock_aberturas(id) on delete restrict,
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(14,2) not null check (precio_unitario >= 0),
  subtotal numeric(14,2) generated always as (cantidad * precio_unitario) stored
);

create sequence if not exists remitos_nro_seq start with 2500 increment by 1;

create table if not exists remitos (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null unique references pedidos(id) on delete cascade,
  nro_remito bigint not null unique default nextval('remitos_nro_seq'),
  fecha date not null default current_date,
  created_at timestamptz default now()
);

create table if not exists proveedores_facturas (
  id bigint generated by default as identity primary key,
  razon_social text not null unique,
  cuit_cuil text,
  rubro text,
  created_at timestamptz default now()
);

create table if not exists movimientos (
  id bigint generated by default as identity primary key,
  proveedor_id bigint references proveedores_facturas(id) on delete set null,
  razon_social text not null,
  cuit_cuil text,
  rubro text,
  fecha date not null,
  nro_factura text not null,
  importe numeric(14,2) not null check (importe >= 0),
  created_at timestamptz default now()
);

do $$
begin
  if not exists (select 1 from pg_type where typname = 'metodo_pago') then
    create type metodo_pago as enum ('Efectivo', 'Transferencia');
  end if;
end
$$;

create table if not exists pagos (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references pedidos(id) on delete cascade,
  fecha date not null,
  monto numeric(14,2) not null check (monto > 0),
  metodo metodo_pago not null,
  created_at timestamptz default now()
);

create or replace view saldos_pedidos as
select
  p.id as pedido_id,
  p.fecha,
  p.total,
  c.id as cliente_id,
  c.nro_cliente,
  c.razon_social,
  coalesce(sum(pg.monto), 0) as pagado,
  p.total - coalesce(sum(pg.monto), 0) as saldo
from pedidos p
join clientes c on c.id = p.cliente_id
left join pagos pg on pg.pedido_id = p.id
group by p.id, c.id;

-- RLS: esta app interna usa Supabase Auth.
-- Las políticas permiten operar solo con usuarios autenticados.
alter table clientes enable row level security;
alter table stock_aberturas enable row level security;
alter table pedidos enable row level security;
alter table pedido_items enable row level security;
alter table remitos enable row level security;
alter table proveedores_facturas enable row level security;
alter table movimientos enable row level security;
alter table pagos enable row level security;

drop policy if exists "clientes_authenticated_all" on clientes;
drop policy if exists "stock_aberturas_authenticated_all" on stock_aberturas;
drop policy if exists "pedidos_authenticated_all" on pedidos;
drop policy if exists "pedido_items_authenticated_all" on pedido_items;
drop policy if exists "remitos_authenticated_all" on remitos;
drop policy if exists "proveedores_facturas_authenticated_all" on proveedores_facturas;
drop policy if exists "movimientos_authenticated_all" on movimientos;
drop policy if exists "pagos_authenticated_all" on pagos;

create policy "clientes_authenticated_all" on clientes
for all to authenticated
using (true)
with check (true);

create policy "stock_aberturas_authenticated_all" on stock_aberturas
for all to authenticated
using (true)
with check (true);

create policy "pedidos_authenticated_all" on pedidos
for all to authenticated
using (true)
with check (true);

create policy "pedido_items_authenticated_all" on pedido_items
for all to authenticated
using (true)
with check (true);

create policy "remitos_authenticated_all" on remitos
for all to authenticated
using (true)
with check (true);

create policy "proveedores_facturas_authenticated_all" on proveedores_facturas
for all to authenticated
using (true)
with check (true);

create policy "movimientos_authenticated_all" on movimientos
for all to authenticated
using (true)
with check (true);

create policy "pagos_authenticated_all" on pagos
for all to authenticated
using (true)
with check (true);

-- Storage para adjuntos de pedidos
insert into storage.buckets (id, name, public)
values ('pedido-archivos', 'pedido-archivos', false)
on conflict (id) do update set public = false;

drop policy if exists "pedido_archivos_select" on storage.objects;
drop policy if exists "pedido_archivos_insert" on storage.objects;
drop policy if exists "pedido_archivos_update" on storage.objects;
drop policy if exists "pedido_archivos_delete" on storage.objects;

create policy "pedido_archivos_select"
on storage.objects for select
to authenticated
using (bucket_id = 'pedido-archivos');

create policy "pedido_archivos_insert"
on storage.objects for insert
to authenticated
with check (bucket_id = 'pedido-archivos');

create policy "pedido_archivos_update"
on storage.objects for update
to authenticated
using (bucket_id = 'pedido-archivos')
with check (bucket_id = 'pedido-archivos');

create policy "pedido_archivos_delete"
on storage.objects for delete
to authenticated
using (bucket_id = 'pedido-archivos');
